imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@ApiBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        fos_csrf_provider: "@form.csrf_provider"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

#FOSUserBundle
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: AppBundle\Entity\User

#FOSRestBundle
fos_rest:
    disable_csrf_role:    null
    access_denied_listener:
        enabled:              false
        service:              null
        formats:

            # Prototype
            name:                 ~
    unauthorized_challenge:  null
    param_fetcher_listener:
        enabled:              false
        force:                false
        service:              null
    cache_dir:            '%kernel.cache_dir%/fos_rest'
    allowed_methods_listener:
        enabled:              false
        service:              null
    routing_loader:
        default_format:       null
        include_format:       true
    body_converter:
        enabled:              false
        validate:             false
        validation_errors_argument:  validationErrors
    service:
        router:               router
        templating:           templating
        serializer:           null
        view_handler:         fos_rest.view_handler.default
        exception_handler:    fos_rest.view.exception_wrapper_handler
        inflector:            fos_rest.inflector.doctrine
        validator:            validator
    serializer:
        version:              null
        groups:               []
        serialize_null:       false
    view:
        default_engine:       twig
        force_redirects:

            # Prototype
            name:                 ~
        mime_types:
            enabled:              false
            service:              null
            formats:

                # Prototype
                name:                 ~
        formats:

            # Prototype
            name:                 ~
        templating_formats:

            # Prototype
            name:                 ~
        view_response_listener:
            enabled:              false
            force:                false
            service:              null
        failed_validation:    400
        empty_content:        204
        exception_wrapper_handler:  null
        serialize_null:       false
        jsonp_handler:
            callback_param:       callback
            mime_type:            application/javascript+jsonp