api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix:   /api

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
homepage:
    path:   /
    defaults:  { _controller: AppBundle:Home:index }
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

appointments:
    type: rest
    resource: ApiBundle\Controller\AppointmentsController

