app:
    resource: "@AppBundle/Controller/"
    type:     annotation

homepage:
    path:   /
    defaults:  { _controller: AppBundle:Home:index }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

api_users:
    type: rest
    prefix: /api
    resource: "@ApiBundle/Resources/config/users_routes.yml"

api_appointments:
    type: rest
    prefix: /api
    resource: "@ApiBundle/Resources/config/appointments_routes.yml"