app:
    resource: "@AppBundle/Controller/"
    type:     annotation
homepage:
    path:   /
    defaults:  { _controller: AppBundle:Home:index }
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

