# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
    app.form.edit:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_profile }
    app.profile.edit:
        class: AppBundle\EventListener\ProfileEditSucces
        arguments: [@router]
        tags:
            - { name: kernel.event_subscriber }
    app.registration.comfermed:
            class: AppBundle\EventListener\RegistrationListener
            arguments: [%mailer_user%, '@router', '@mailer', '@service_container']
            tags:
                - { name: kernel.event_subscriber }
    app.changepassword.change:
        class: AppBundle\EventListener\ChangePasswordSucces
        arguments: [@router]
        tags:
            - { name: kernel.event_subscriber }      